[% INCLUDE $header %]

[% FOREACH line IN lines %]
	[% timepoint = line.shift %]
# Time point: [% fortmatTime( $timepoint ) %]
	[% FOREACH var IN vars %]
		[% index = 0 %]
		[% FOREACH info IN $var.kks %]
			[% value = formatValue( $line( $index ), $var.format) %]
			[% rel = $line( $index + 1 ) %]
			[% index = $index + 2 %]
			[% SWITCH $var.dim %]
			[% CASE 0 %]
[% $value %][% "\t" %][% $rel %]
			[% CASE 1 %]
[% $info.index1 %][% "\t" %][% $value %][% "\t" %][% $rel %]
			[% CASE 2 %]
[% $info.index1 %][% "\t" %][% $info.index2 %][% "\t" %][% $value %][% "\t" %][% $rel %]
			[% END %]
		[% END %] 
	[% END %] 
[% END %]